title: Mr. Sampad Mandal
first_name: Mr. Sampad
middle_name: 
last_name: Mandal
e-mail: mandalsampad1995@hmail.com
# logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
